// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYiIUNR1qRCWEJR1T56_nfqOjkT3Tk80',
    appId: '1:21008139011:android:aa0d502a573fe165dcdf36',
    messagingSenderId: '21008139011',
    projectId: 'trysearch-678e2',
    databaseURL: 'https://trysearch-678e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trysearch-678e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGwK3cl1H6y3ql6717pVvFns-A2eFzJ0',
    appId: '1:21008139011:ios:f72ebdd0054c1caedcdf36',
    messagingSenderId: '21008139011',
    projectId: 'trysearch-678e2',
    databaseURL: 'https://trysearch-678e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trysearch-678e2.firebasestorage.app',
    iosClientId: '21008139011-4dcdmiaah8t77k5uah0ij03mc6ar9ls8.apps.googleusercontent.com',
    iosBundleId: 'com.rafsan.growup099',
  );
}
